### PR TITLE
Export the library as UMD format

### PR DESCRIPTION
**Pull request by cosminnicula**
Support for AMD, CommonJS2 and global variable. Related with #164

### CODE REVIEW

**Comment by cosminnicula** [comment]
This should also be published on NPM.

**Comment by jquense** [comment]
Can you walk me through why you need this? The npm package is already in CommonJS format, why not just consume the modules instead of the dist build?

**Comment by cosminnicula** [comment]
The use case is documented in #164. It's mostly because other projects / applications might already consume AMD-format packages or global variables. By limiting the package to be consumed only as CommonJS, you exclude those type of applications.

Other libraries already have umd as a default output:
- Facebook's FixedDataTable https://github.com/facebook/fixed-data-table/blob/master/webpack.config.js
- React Router https://github.com/rackt/react-router/blob/master/webpack.config.js
- React Bootstrap https://github.com/react-bootstrap/react-bootstrap/blob/master/webpack/webpack.config.js

Please merge both commits in this PR before publishing to NPM.

**Comment by jquense** [comment]
merging since its easy enough for me to provide this, but do want to say that, using the dist/ build is generally not recommended for a variety of reasons, that make it less useful then using something like browserify or webpack, but you are certainly welcome to it if thats what you need :)

**Comment by cosminnicula** [comment]
Yes, I know and you're right.
But there are projects out there that are still relying on AMD format or global variables and do their build with Maven. You cannot force them to consume a library as CommonJS or use browserify or webpack. We should care about the poor :)

**Comment by cosminnicula** [comment]
Can you publish this on NPM? Thanks!

**Pull request merged**
