### PR TITLE
Replaced React.createClass with create-react-class

### PR DESCRIPTION
**Pull request by joshgagnon**
Also have replaced isMounted with checks to this._mounted, which is managed by life cycle functions.

### CODE REVIEW

**Comment by zerkms** [comment]
A note from the react documentation:

> Along with functional components, JavaScript classes are now the preferred way to create components in React.

What is the reason to not use the officially preferred way with ES2015 classes, but ancient createClasses thing?

**Comment by joshgagnon** [comment]
The reason is this library uses a handful of mixins, and would need a major revision to move over to ES2015 classes.

**Comment by jquense** [comment]
Thanks!

**Comment by ericvilleneuve** [comment]
Any chance we can get a 3.4.9 release including this PR?

**Comment by sylvain-hamel** [comment]
@jquense would you please release the npm package with this fix? Thanks

**Comment by waynebrantley** [comment]
@jquense Any changes for npm package?   Or are you just going to release 4.0 instead?

**Pull request merged**
