### PR TITLE
try adding nodeRef

### LINKED ISSUE #1137: findDOMNode is deprecated in StrictMode - error
Im getting this error with the combobox. 

react_devtools_backend.js:4026 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition2 which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:

image

### PR DESCRIPTION
**Pull request by quinn**
attempt to fix #1137

### CODE REVIEW

**Comment by quinn** [comment]
@jquense looks like I need to refactor because its a class-based component.

**Comment by bt** [comment]
Is `useRef` the same as `React.createRef`?

You can use `createRef` in class-based components.

**Comment by quinn** [comment]
@bt yes, it is the same. I updated to use createRef. @jquense what is a good way to test this out?

**Comment by jquense** [comment]
Try running the docs but in strict mode?

**Comment by bt** [comment]
@quinn Did you have any luck?

**Comment by astralmedia** [comment]
Any movement on this? Would love to clean that last error up on my logs :)

**Comment by quinn** [comment]
@astralmedia PR should work, I haven't had a chance to run the docs in strict mode as advised

**Comment by quinn** [comment]
also, I can't see why the build failed? says, expired

**Comment by quinn** [comment]
getting this error when I try to run docs:

```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
```

**Comment by grobux** [comment]
Hi, can this PR be merged or does it needs more work?
I face the issue it should be fixing

**Comment by jquense** [comment]
I've incorporated these changes in v5.8.5

**Pull request closed without merging**
