### PR TITLE
Fix problem typing decimals in NumberPicker (#811).

### PR DESCRIPTION
**Pull request by sanason**
Entirely plagiarized from 665ad7e7bf302ede211f6a45c59559131432ca83.

### CODE REVIEW

**Comment by jquense** [comment]
thanks!

**Comment by sanason** [comment]
Thanks for merging!

**Comment by sanason** [comment]
Might this get itself into a release? I'm not sure how releases are scheduled.

**Comment by jquense** [comment]
released in 4.4.7!

**Pull request merged**
