### PR TITLE
Use transpiled index.js instead of localizer.js

### PR DESCRIPTION
**Pull request by balmma**
Consistency across packages and no need do special handling for react-widgets-simple-number.

### CODE REVIEW

**Comment by jquense** [comment]
thanks! i'll push a release a bit later

**Comment by samalexander** [comment]
@jquense, when are you planning to cut a release with this fix in? It is blocking us from using the NumberPicker component (outside of switching everything to Globalize). Thanks for all your help!

**Comment by balmma** [comment]
For the time being you can transpile the localizer.js file manually (even online at  https://babeljs.io/repl/) and require the transpiled file directly. After the release you just have to change it back to the module.

**Comment by obrejla** [comment]
Hi, when do you think the new version will be released? Thanks.

**Pull request merged**
