### PR TITLE
Disable weekends and certain dates

### PR DESCRIPTION
**Pull request by timneyens**
I created an update so that the weekends and certain dates can be disabled in the datepicker.

### CODE REVIEW

**Comment by jquense** [comment]
thanks for the PR. I think i'd to handle something like this more generally. Instead of an array of dates, the calendar could accept a `isDisabled` function that is called on each date as they are rendered, then the user can pick and choose any criteria they want for disabling dates

**Comment by timneyens** [comment]
Thanks for the reply, I removed the previous code and added a new param 'isDateDisabled'. This is a function which checks if a date should be disabled or not.

**Comment by QuantumHive** [comment]
I need this behavior, when do you plan to merge this PR?

**Comment by jquense** [comment]
long time coming but can you rebase this?

**Comment by timneyens** [comment]
Done ;)

**Comment by Shadowman4205** [comment]
Hello, is this functionality available on main?

**Comment by rishitank** [comment]
Hi, will this pull request be merged to master soon? This feature is crucial for me, thanks.

**Comment by papiro** [comment]
Does anybody have a work-around to allow disabling certain dates?

**Comment by papiro** [comment]
My work-around goes something like this:

```
DayComponent ({date, label}) {
  if (this.props.disableWeekends) {
    const dayOfWeek = date.getDay();
    isValidDate = dayOfWeek > 0 && dayOfWeek < 6;
  }

  return (
    <div 
      className={styles.calendarCell}
      onClick={evt => {
        !isValidDate && evt.stopPropagation();
      }}
    >
      {label}
    </div>
  )
}
```
I made the `DayComponent` a method on my DateTimePicker class so that I could reference props and state. I also added some css like so:
```
.rw-cell {
  padding: 0;
  border: none;
}

:local(.calendarCell) {
  padding: 0.25rem;
}
```
This css is so the custom DayComponent takes up the full `<td>` so no clicks escape it. Of course, you can style the disabled cells how you wish.

**Comment by trevorhex** [comment]
@alejandrovillegas can this please be merged? id rather not have to rework and switch to a different component  😝

**Pull request closed without merging**
